# Generated by Django 5.0.6 on 2024-06-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reg_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_user',
            old_name='name',
            new_name='username',
        ),
    ]
